<?php

return[
    "/" => ["controller" => "App\Controller\PageController", "action" => "acceuil"],
    "/inscription/" => ["controller" => "App\Controller\UserController", "action" => "inscription"],
    "/inscriptionEmploye/" => ["controller" => "App\Controller\UserController", "action" => "inscriptionEmploye"],
    "/connexion/" => ["controller" => "App\Controller\UserController", "action" => "connexion"],
    "/mesInfos/" => ["controller" => "App\Controller\UserController", "action" => "afficheInfos"],
    "/modifierInfos/" => ["controller" => "App\Controller\UserController", "action" => "modifierInfos"],
    "/modificationMotDePasse/" => ["controller" => "App\Controller\UserController", "action" => "modifierMdp"],
    "/motDePasseOublie/" => ["controller" => "App\Controller\UserController", "action" => "reinitialiserMdp"],
    "/gestionEmployes/" => ["controller" => "App\Controller\UserController", "action" => "afficheEmploye"],
    "/detailEmploye/" => ["controller" => "App\Controller\UserController", "action" => "afficheInfosEmploye"],
    "/supprimerMonCmpte/" => ["controller" => "App\Controller\UserController", "action" => "supprimerCompteUtilisateur"],
    "/supprimerCompteEmploye/" => ["controller" => "App\Controller\UserController", "action" => "supprimerCompteEmploye"],
    "/creeTypeDePlats/" => ["controller" => "App\Controller\TypeDePlatController", "action" => "creerTypeDePlat"],
    //"/plats/" => ["controller" => "App\Controller\TypeDePlatController", "action" => "afficherTypeDePlat"],
    "/modifierTypeDePlat/" => ["controller" => "App\Controller\TypeDePlatController", "action" => "modifierTypeDePlat"],
    "/supprimerTypeDePlat/" => ["controller" => "App\Controller\TypeDePlatController", "action" => "supprimerTypeDePlat"],
    "/creerPlat/" => ["controller" => "App\Controller\PlatController", "action" => "creerPlat"],
    "/plats/" => ["controller" => "App\Controller\PlatController", "action" => "afficherPlat"],
    "/detailPlat/" => ["controller" => "App\Controller\PlatController", "action" => "afficherDetailPlat"],
    "/modifierPlat/" => ["controller" => "App\Controller\PlatController", "action" => "modifierPlat"],
    "/supprimerPlat/" => ["controller" => "App\Controller\PlatController", "action" => "supprimerPlat"],
    "/modifierStatusPlat/" => ["controller" => "App\Controller\PlatController", "action" => "modifierStatusPlat"],
    "/creerMenu/" => ["controller" => "App\Controller\MenuController", "action" => "creerMenu"],
    "/menu/" => ["controller" => "App\Controller\MenuController", "action" => "afficherMenus"],
    "/detailMenu/" => ["controller" => "App\Controller\MenuController", "action" => "afficherDetailMenu"],
    "/menuFiltre/" => ["controller" => "App\Controller\MenuController", "action" => "afficherMenuFiltre"],
    "/modifierMenu/" => ["controller" => "App\Controller\MenuController", "action" => "modifierMenu"],
    "/modifierStatusMenu/" => ["controller" => "App\Controller\MenuController", "action" => "modifierStatusMenu"],
    "/supprimerMenu/" => ["controller" => "App\Controller\MenuController", "action" => "supprimerMenu"],
    "/creerTypeDePresta/" => ["controller" => "App\Controller\TypeDePrestaController", "action" => "creerTypeDePresta"],
    //"/prestations/" => ["controller" => "App\Controller\TypeDePrestaController", "action" => "afficherTypeDePresta"],
    "/modifierTypeDePresta/" => ["controller" => "App\Controller\TypeDePrestaController", "action" => "modifierTypeDePresta"],
    "/supprimerTypeDePresta/" => ["controller" => "App\Controller\TypeDePrestaController", "action" => "supprimerTypeDePresta"],
    "/creerPrestation/" => ["controller" => "App\Controller\PrestationController", "action" => "creerPrestation"],
    "/prestations/" => ["controller" => "App\Controller\PrestationController", "action" => "creerPrestation"],
];