name: Tests PHP

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Installer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, pdo, pdo_mysql

      - name: Valider composer.json et composer.lock
        run: composer validate --strict

      - name: Mettre en cache les paquets Composer
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Installer les dépendances
        run: composer install --prefer-dist --no-progress

      - name: Lancer les tests PHPUnit
        run: vendor/bin/phpunit
